// DILF Radio 91.1 Now Playing data. Updated by the scheduled show report.
// Only this file changes on each update. Edit index.html for layout.
window.DILF_SHOWS = {
 "updated": "2026-09-19",
 "prev": null,
 "added": [],
 "removed": [],
 "drive": [
  {"a": "Tab Benoit", "v": "Des Plaines Theatre", "s": "2026-10-04"},
  {"a": "Kenny Wayne Shepherd", "v": "Des Plaines Theatre", "s": "2026-10-15"},
  {"a": "Robin Trower", "v": "Arcada Theatre, St. Charles", "s": "2026-10-14"},
  {"a": "Widespread Panic", "v": "Riverside Theater, Milwaukee", "s": "2026-10-23", "e": "2026-10-25"},
  {"a": "Umphrey's McGee", "v": "Pabst Theater, Milwaukee", "s": "2026-10-09", "e": "2026-10-10"},
  {"a": "Goose", "v": "Miller High Life Theatre, Milwaukee", "s": "2026-11-06", "e": "2026-11-08"},
  {"a": "Christone \"Kingfish\" Ingram", "v": "Turner Hall, Milwaukee", "s": "2026-10-18"},
  {"a": "Buddy Guy", "v": "Rialto Square Theatre, Joliet", "s": "2026-10-16"}
 ],
 "shows": [
  {"c": "b", "s": "2026-09-19", "a": "Beth Hart", "n": "Blues-rock powerhouse", "v": "Riviera Theatre", "mi": 7.3},
  {"c": "b", "s": "2026-09-29", "e": "2026-10-07", "a": "Ben Harper & The Innocent Criminals", "n": "7-night residency: Sep 29-30, Oct 2-4, 6-7", "v": "Garcia's Chicago", "mi": 1.5},
  {"c": "b", "s": "2026-10-02", "a": "Lil Ed & the Blues Imperials", "n": "Chicago slide-guitar blues", "v": "Buddy Guy's Legends", "mi": 0.9},
  {"c": "b", "s": "2026-10-03", "a": "Curtis Salgado", "n": "Blues and soul singer, harmonica", "v": "Buddy Guy's Legends", "mi": 0.9},
  {"c": "b", "s": "2026-10-04", "a": "The Revivalists + Robert Randolph", "n": "Randolph's sacred-steel guitar opens", "v": "The Salt Shed (Fairgrounds)", "mi": 2},
  {"c": "b", "s": "2026-10-08", "a": "JW Jones", "n": "Canadian blues guitarist", "v": "Buddy Guy's Legends", "mi": 0.9},
  {"c": "b", "s": "2026-10-09", "a": "Davy Knowles", "n": "Blues-rock guitarist", "v": "SPACE", "mi": 12},
  {"c": "b", "s": "2026-10-14", "a": "Ivy Ford", "n": "Chicago blues guitarist", "v": "Hey Nonny", "mi": 23},
  {"c": "b", "s": "2026-10-15", "a": "Jesse Roper", "n": "Blues-rock guitar", "v": "FitzGerald's", "mi": 10},
  {"c": "b", "s": "2026-10-16", "a": "King's X", "n": "", "v": "House of Blues", "mi": 0.4},
  {"c": "b", "s": "2026-10-19", "a": "Albert Cummings", "n": "Blues guitarist", "v": "SPACE", "mi": 12},
  {"c": "b", "s": "2026-10-20", "e": "2026-10-21", "a": "The Black Keys", "n": "Two nights", "v": "The Salt Shed (Shed)", "mi": 2},
  {"c": "b", "s": "2026-10-21", "a": "Adrian Belew, Steve Vai, Tony Levin, Terry Bozzio", "n": "Guitar-heavy supergroup", "v": "Copernicus Center", "mi": 10},
  {"c": "b", "s": "2026-10-23", "e": "2026-10-27", "a": "Tedeschi Trucks Band", "n": "With Lukas Nelson. Oct 23, 24, 26, 27", "v": "Chicago Theatre", "mi": 0.2},
  {"c": "b", "s": "2026-10-29", "a": "Dweezil Zappa", "n": "", "v": "Riviera Theatre", "mi": 7.3},
  {"c": "b", "s": "2026-11-08", "a": "Alice Cooper", "n": "", "v": "Genesee Theatre", "mi": 37},
  {"c": "b", "s": "2026-11-16", "a": "Keb' Mo'", "n": "", "v": "North Shore Center", "mi": 13},
  {"c": "b", "s": "2026-11-24", "a": "John Primer", "n": "Muddy Waters' last guitarist", "v": "Hey Nonny", "mi": 23},
  {"c": "b", "s": "2026-11-24", "a": "Black Label Society + Zakk Sabbath", "n": "Zakk Wylde, twice", "v": "Byline Bank Aragon Ballroom", "mi": 7.3},
  {"c": "b", "s": "2026-12-02", "a": "Corky Siegel", "n": "Chicago blues harmonica", "v": "Hey Nonny", "mi": 23},
  {"c": "b", "s": "2026-12-13", "a": "Cyril Neville", "n": "New Orleans funk and blues", "v": "FitzGerald's", "mi": 10},
  {"c": "b", "s": "2027-01-08", "e": "2027-01-09", "a": "Led Zeppelin 2", "n": "Zeppelin tribute, two nights", "v": "House of Blues", "mi": 0.4, "isNew": true},
  {"c": "b", "s": "2027-02-19", "a": "Jackie Venson", "n": "Austin blues guitarist", "v": "Logan Center (UChicago)", "mi": 7.5},
  {"c": "b", "s": "2027-03-18", "a": "Randy Hansen", "n": "Jimi Hendrix tribute (rescheduled)", "v": "Garcia's Chicago", "mi": 1.5},
  {"c": "b", "s": "2027-04-01", "a": "The Psychedelic Furs + Living Colour", "n": "Vernon Reid and Living Colour on the bill", "v": "Genesee Theatre", "mi": 37, "isNew": true},
  {"c": "j", "s": "2026-09-23", "a": "Charlie Hunter Trio", "n": "", "v": "Garcia's Chicago", "mi": 1.5},
  {"c": "j", "s": "2026-09-24", "a": "Brown Eyed Women", "n": "Grateful Dead tribute, with Bella Rayne Band", "v": "Garcia's Chicago", "mi": 1.5, "t": "Tribute"},
  {"c": "j", "s": "2026-09-24", "a": "Karl Denson's Tiny Universe", "n": "", "v": "Chop Shop", "mi": 3},
  {"c": "j", "s": "2026-09-25", "a": "Hyryder", "n": "Grateful Dead tribute", "v": "Martyrs'", "mi": 6, "t": "Tribute"},
  {"c": "j", "s": "2026-09-26", "a": "The Polish Ambassador: Polish Phish", "n": "Electronic Phish reworks", "v": "Garcia's Chicago", "mi": 1.5},
  {"c": "j", "s": "2026-09-26", "a": "Delvon Lamarr Organ Trio", "n": "", "v": "FitzGerald's", "mi": 10},
  {"c": "j", "s": "2026-09-27", "a": "The Polish Ambassador: Dead Polish", "n": "Electronic Grateful Dead reworks", "v": "Garcia's Chicago", "mi": 1.5},
  {"c": "j", "s": "2026-10-02", "a": "Joe Russo's Almost Dead", "n": "", "v": "The Salt Shed (Shed)", "mi": 2},
  {"c": "j", "s": "2026-10-02", "a": "Fruition", "n": "", "v": "Old Town School of Folk Music", "mi": 7},
  {"c": "j", "s": "2026-10-03", "a": "Bruce Hornsby & the Noisemakers", "n": "Played keys with the Dead 1990-92", "v": "Cahn Auditorium", "mi": 12},
  {"c": "j", "s": "2026-10-08", "e": "2026-10-09", "a": "Karina Rykman", "n": "Two nights", "v": "Garcia's Chicago", "mi": 1.5},
  {"c": "j", "s": "2026-10-16", "a": "Grateful String Band", "n": "Bluegrass Grateful Dead", "v": "Garcia's Chicago", "mi": 1.5, "t": "Tribute"},
  {"c": "j", "s": "2026-10-18", "a": "John Scofield, Oteil Burbridge, Larry Goldings, Adam Deitch", "n": "Oteil of Dead & Company", "v": "Thalia Hall", "mi": 3},
  {"c": "j", "s": "2026-10-19", "a": "Eggy", "n": "The Final Tour (acoustic)", "v": "Garcia's Chicago", "mi": 1.5},
  {"c": "j", "s": "2026-10-22", "a": "Houseplant", "n": "", "v": "Garcia's Chicago", "mi": 1.5},
  {"c": "j", "s": "2026-10-25", "a": "Cris Jacobs Pirate's Ball", "n": "Tribute night", "v": "Garcia's Chicago", "mi": 1.5},
  {"c": "j", "s": "2026-10-30", "a": "Taper's Choice", "n": "Grateful Dead tribute", "v": "Garcia's Chicago", "mi": 1.5, "t": "Tribute"},
  {"c": "j", "s": "2026-10-31", "e": "2026-11-01", "a": "Dumpstaphunk", "n": "Halloween weekend, two nights", "v": "Garcia's Chicago", "mi": 1.5},
  {"c": "j", "s": "2026-11-05", "a": "Pigeons Playing Ping Pong", "n": "With Dizgo", "v": "The Vic Theatre", "mi": 4.3},
  {"c": "j", "s": "2026-11-06", "a": "Julian Lage", "n": "With John Medeski", "v": "Cahn Auditorium", "mi": 12},
  {"c": "j", "s": "2026-11-07", "a": "Dave Matthews Band", "n": "", "v": "United Center", "mi": 2},
  {"c": "j", "s": "2026-11-07", "e": "2026-11-08", "a": "REPRISE", "n": "Recreating classic Phish shows, two nights", "v": "Garcia's Chicago", "mi": 1.5, "t": "Tribute"},
  {"c": "j", "s": "2026-11-08", "a": "The Samples", "n": "", "v": "Chop Shop", "mi": 3},
  {"c": "j", "s": "2026-11-11", "a": "Donna the Buffalo", "n": "", "v": "Garcia's Chicago", "mi": 1.5},
  {"c": "j", "s": "2026-11-13", "a": "Sicard Hollow", "n": "", "v": "Reggies", "mi": 2.8},
  {"c": "j", "s": "2026-11-13", "a": "Mr. Blotto", "n": "Chicago jam institution", "v": "Hey Nonny", "mi": 23},
  {"c": "j", "s": "2026-11-13", "e": "2026-11-14", "a": "Sam Grisman Project", "n": "Garcia/Grisman songbook, two nights", "v": "Garcia's Chicago", "mi": 1.5},
  {"c": "j", "s": "2026-11-14", "a": "Little Feat", "n": "", "v": "North Shore Center", "mi": 13},
  {"c": "j", "s": "2026-11-14", "a": "Grateful Shred", "n": "Grateful Dead tribute", "v": "Park West", "mi": 2.6, "t": "Tribute"},
  {"c": "j", "s": "2026-11-18", "a": "Jackie Greene", "n": "Ex-Phil Lesh & Friends", "v": "Garcia's Chicago", "mi": 1.5},
  {"c": "j", "s": "2026-11-20", "e": "2026-11-21", "a": "WookieFoot", "n": "Two nights", "v": "Reggies", "mi": 2.8},
  {"c": "j", "s": "2026-11-20", "e": "2026-11-21", "a": "Mountain Grass Unit", "n": "Two nights", "v": "Garcia's Chicago", "mi": 1.5},
  {"c": "j", "s": "2026-11-21", "a": "The Wood Brothers", "n": "", "v": "Cahn Auditorium", "mi": 12},
  {"c": "j", "s": "2026-11-27", "a": "The Werks", "n": "Werksgiving, with Big Blitz", "v": "Garcia's Chicago", "mi": 1.5},
  {"c": "j", "s": "2026-12-05", "a": "Spafford", "n": "", "v": "Park West", "mi": 2.6},
  {"c": "j", "s": "2026-12-18", "e": "2026-12-20", "a": "moe.", "n": "Three nights in a 300-cap room. On sale now", "v": "Garcia's Chicago", "mi": 1.5, "isNew": true},
  {"c": "j", "s": "2026-12-30", "e": "2026-12-31", "a": "Greensky Bluegrass", "n": "New Year's run", "v": "The Salt Shed (Shed)", "mi": 2},
  {"c": "j", "s": "2027-01-08", "a": "G. Love & Special Sauce", "n": "Just added. Tickets on sale", "v": "Garcia's Chicago", "mi": 1.5, "isNew": true}
 ]
};
